package UI;


/**
 *
 * @author Malab
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Puntaje1 = new javax.swing.JLabel();
        Username1 = new javax.swing.JLabel();
        Username2 = new javax.swing.JLabel();
        Puntaje2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        CartaJugador2 = new javax.swing.JLabel();
        CartaJugador1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Puntaje1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        Puntaje1.setForeground(new java.awt.Color(100, 100, 100));
        Puntaje1.setText("0/0");
        getContentPane().add(Puntaje1);
        Puntaje1.setBounds(150, 10, 60, 30);

        Username1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        Username1.setForeground(new java.awt.Color(100, 100, 100));
        Username1.setText("Username1");
        getContentPane().add(Username1);
        Username1.setBounds(10, 10, 140, 30);

        Username2.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        Username2.setForeground(new java.awt.Color(100, 100, 100));
        Username2.setText("Username1");
        getContentPane().add(Username2);
        Username2.setBounds(220, 10, 140, 30);

        Puntaje2.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        Puntaje2.setForeground(new java.awt.Color(100, 100, 100));
        Puntaje2.setText("0/0");
        getContentPane().add(Puntaje2);
        Puntaje2.setBounds(360, 10, 60, 30);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(420, -20, 10, 60);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(210, -20, 10, 60);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(-40, 40, 740, 10);

        CartaJugador2.setBackground(new java.awt.Color(255, 50, 50));
        CartaJugador2.setText("Aqui van las cartas");
        CartaJugador2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(CartaJugador2);
        CartaJugador2.setBounds(850, 0, 150, 200);

        CartaJugador1.setBackground(new java.awt.Color(255, 50, 50));
        CartaJugador1.setText("Aqui van las cartas");
        CartaJugador1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(CartaJugador1);
        CartaJugador1.setBounds(700, 0, 150, 200);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CartaJugador1;
    private javax.swing.JLabel CartaJugador2;
    private javax.swing.JLabel Puntaje1;
    private javax.swing.JLabel Puntaje2;
    private javax.swing.JLabel Username1;
    private javax.swing.JLabel Username2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
