package UI;

import java.awt.Color;
import java.awt.image.BufferedImage;

/**
 *
 * @author Malab
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        Puntaje1 = new javax.swing.JLabel();
        Username1 = new javax.swing.JLabel();
        Username2 = new javax.swing.JLabel();
        Puntaje2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        CartaJugador2 = new javax.swing.JLabel();
        CartaJugador1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        RankingB = new javax.swing.JButton();
        CiudadB = new javax.swing.JButton();
        RetoB = new javax.swing.JButton();
        RollDice = new javax.swing.JButton();
        LogOffB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Puntaje1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        Puntaje1.setForeground(new java.awt.Color(100, 100, 100));
        Puntaje1.setText("0/0");
        getContentPane().add(Puntaje1);
        Puntaje1.setBounds(150, 10, 60, 30);

        Username1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        Username1.setForeground(new java.awt.Color(100, 100, 100));
        Username1.setText("Username1");
        getContentPane().add(Username1);
        Username1.setBounds(10, 10, 140, 30);

        Username2.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        Username2.setForeground(new java.awt.Color(100, 100, 100));
        Username2.setText("Username1");
        getContentPane().add(Username2);
        Username2.setBounds(220, 10, 140, 30);

        Puntaje2.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        Puntaje2.setForeground(new java.awt.Color(100, 100, 100));
        Puntaje2.setText("0/0");
        getContentPane().add(Puntaje2);
        Puntaje2.setBounds(360, 10, 60, 30);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(420, -20, 10, 60);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(210, -20, 10, 60);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(-40, 40, 740, 10);

        CartaJugador2.setBackground(new java.awt.Color(255, 50, 50));
        CartaJugador2.setText("Aqui van las cartas");
        CartaJugador2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(CartaJugador2);
        CartaJugador2.setBounds(870, 0, 150, 200);

        CartaJugador1.setBackground(new java.awt.Color(255, 50, 50));
        CartaJugador1.setText("Aqui van las cartas");
        CartaJugador1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(CartaJugador1);
        CartaJugador1.setBounds(710, 0, 150, 200);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 50, 700, 680);

        RankingB.setText("Ranking");
        RankingB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RankingBActionPerformed(evt);
            }
        });
        getContentPane().add(RankingB);
        RankingB.setBounds(430, 0, 100, 40);

        CiudadB.setText("Elegir Ciudad");
        CiudadB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CiudadBActionPerformed(evt);
            }
        });
        getContentPane().add(CiudadB);
        CiudadB.setBounds(740, 200, 100, 23);

        RetoB.setText("Elegir Reto");
        RetoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetoBActionPerformed(evt);
            }
        });
        getContentPane().add(RetoB);
        RetoB.setBounds(890, 200, 100, 23);

        RollDice.setText("RollDice");
        RollDice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RollDiceActionPerformed(evt);
            }
        });
        getContentPane().add(RollDice);
        RollDice.setBounds(800, 530, 150, 170);

        LogOffB.setText("Log Off");
        LogOffB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	LogOffBActionPerformed(evt);
            }
        });
        getContentPane().add(LogOffB);
        LogOffB.setBounds(540, 0, 100, 40);

        pack();
    }// </editor-fold>                        

    private void LogOffBActionPerformed(java.awt.event.ActionEvent evt) {                                         
       LoginWindow login = new LoginWindow();
       
       dispose();
    }  
    private void RankingBActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void CiudadBActionPerformed(java.awt.event.ActionEvent evt) {                                        
    }                                       

    private void RetoBActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void RollDiceActionPerformed(java.awt.event.ActionEvent evt) {                                         
    }                                        

    
    private void PanelMap(BufferedImage mapimage){
		int h = mapimage.getHeight();
		int w = 500 * mapimage.getWidth() / h;

		jPanel1.getGraphics().setColor(Color.BLACK);
		jPanel1.getGraphics().drawRect(0, 0, 2000, 2000);
		jPanel1.getGraphics().fillRect(0, 0, 2000, 2000);
		jPanel1.getGraphics().drawImage(mapimage, jPanel1.getWidth() / 4, jPanel1.getHeight() / 4, null);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel CartaJugador1;
    private javax.swing.JLabel CartaJugador2;
    private javax.swing.JButton CiudadB;
    private javax.swing.JButton LogOffB;
    private javax.swing.JLabel Puntaje1;
    private javax.swing.JLabel Puntaje2;
    private javax.swing.JButton RankingB;
    private javax.swing.JButton RetoB;
    private javax.swing.JButton RollDice;
    private javax.swing.JLabel Username1;
    private javax.swing.JLabel Username2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration                   
}
